SELECT COUNT(T.ID) AS FISH_COUNT, MAX(T.LENGTH) AS MAX_LENGTH, T.FISH_TYPE
FROM (SELECT ID, FISH_TYPE,
      CASE 
        WHEN LENGTH <= 10 || LENGTH IS NULL 
        THEN 10 
        ELSE LENGTH 
        END AS LENGTH
      FROM FISH_INFO) T
GROUP BY T.FISH_TYPE
HAVING AVG(T.LENGTH) >= 33
ORDER BY T.FISH_TYPE;
