-- FOOD_PRODUCT, FOOD_ORDER 
-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출 조회 
-- order by 총매출 desc, 식품 ID asc 


-- PRODUCT_ID 가 공통이다 

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
    AND YEAR(O.PRODUCE_DATE) = 2022
     AND MONTH(O.PRODUCE_DATE) = 05
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;

