-- 년, 월, 성별 별로 상품을 구매한 회원수 집계 
-- order by 년, 월, 성별 asc 
-- 성별 정보 NULL이면 결과에서 제외할 것 

SELECT S.YEAR, S.MONTH, I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO I
JOIN (SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
      FROM ONLINE_SALE) AS S
ON S.USER_ID = I.USER_ID 
WHERE I.GENDER IS NOT NULL
GROUP BY 1, 2, 3     
ORDER BY 1, 2, 3