-- 대장균 개체 크기가 100이하면 LOW, 100초과 1000이하면 MEDIUM, 1000초과면 HIGH로 분류 
-- ID, SIZE 출력
-- order by id asc

SELECT ID, CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW' 
                WHEN SIZE_OF_COLONY BETWEEN 101 AND 1000 THEN 'MEDIUM' 
                WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH' END AS SIZE
FROM ECOLI_DATA
ORDER BY 1