-- 물고기 종류 별 가장 큰 물고기의 ID, 물고기 이름 FISH_NAME, 길이 LENGTH
-- order by id asc

WITH TYPE_NAME AS (
    SELECT F.ID, F.FISH_TYPE, N.FISH_NAME, F.LENGTH
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO N
    ON F.FISH_TYPE = N.FISH_TYPE
),
MAX_LENGTH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE   
)
SELECT T.ID, T.FISH_NAME, M.LENGTH
FROM TYPE_NAME T
JOIN MAX_LENGTH M
ON T.FISH_TYPE = M.FISH_TYPE AND T.LENGTH = M.LENGTH


