-- 부모의 형질을 모두 보유한 대장균의 ID, 대장균의 GENOTYPE, 부모 대장균의 형질 PARENT_GENOTYPE 출력 
-- order by ID asc

SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PARENT
JOIN (SELECT ID, PARENT_ID, GENOTYPE
      FROM ECOLI_DATA) CHILD
ON PARENT.ID = CHILD.PARENT_ID
WHERE CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC