-- 각 분기별 분화된 대장균의 개체 의 총 수 (ECOLI_COOUNT)
-- 각 분기에 Q 붙이기 
-- order by 분기 asc (quarter)

SELECT E.QUARTER, COUNT(E.ID) AS ECOLI_COUNT
FROM (SELECT (CASE WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
          WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
          WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
          WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN '4Q' END) AS QUARTER, ID
     FROM ECOLI_DATA
     ) AS E
GROUP BY E.QUARTER
ORDER BY 1;