SELECT I.INGREDIENT_TYPE, SUM(H.TOTAL_ORDER)
FROM FIRST_HALF H
JOIN ICECREAM_INFO I ON H.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY 2

-- 처음엔 무작정 조인을 했다. 
-- 조인을 해버리면 FLAVOR 의 일부 정보만 넘어가기 때문에 답이 틀린 것... 