SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO P ON T.PARENT_ITEM_ID = P.ITEM_ID
JOIN ITEM_INFO C ON T.ITEM_ID = C.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY ITEM_ID DESC

-- 같은 테이블 (ITEM_INFO)를 두 번 조인해서 
-- 한 번은 PARENT 정보 가져오고, 다른 한 번은 CHILD 정보 가져온다 