WITH ECOLI_DATA2 AS (
    SELECT E1.ID, E2.YEAR, E2.SIZE_OF_COLONY, E1.PARENT_ID
    FROM ECOLI_DATA E1
    JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, ID 
          FROM ECOLI_DATA) AS E2
    ON E1.ID = E2.ID
)
SELECT EMAX.YEAR, (EMAX.MX - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID 
FROM ECOLI_DATA2 AS E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MX
      FROM ECOLI_DATA 
      GROUP BY YEAR(DIFFERENTIATION_DATE)) AS EMAX
ON E.YEAR = EMAX.YEAR
ORDER BY 1, 2

