-- 보호 기간이 가장 길었던 동물 두 마리의 아이디, 이름 조회 
-- order by 보호 기간 desc 

-- ANIMAL_INS 의 DATETIME과 ANIMAL_OUTS 의 DATETIME이 가장 큰 거 LIMIT 2

SELECT D.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN (SELECT O.ANIMAL_ID, DATEDIFF(O.DATETIME, I2.DATETIME) AS DIFF
      FROM ANIMAL_OUTS O, ANIMAL_INS I2
      WHERE O.ANIMAL_ID = I2.ANIMAL_ID) D
ON I.ANIMAL_ID = D.ANIMAL_ID
ORDER BY D.DIFF DESC
LIMIT 2