-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회 
-- order by 시간순 

WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 AS HOUR FROM HOURS WHERE HOUR < 23)
SELECT HOURS.HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM HOURS
LEFT JOIN ANIMAL_OUTS O
ON HOURS.HOUR = HOUR(O.DATETIME)
GROUP BY HOURS.HOUR
ORDER BY HOURS.HOUR

