-- 2022년 10월 5일 등록된 중고거래 게시물의 
-- 게시글 ID, 작성자 ID, 게시글 제목, 가격, 거래상태 조회 
-- SALE : 판매중, RESERVED : 예약중, DONE : 거래완료
# SELECT * FROM USED_GOODS_BOARD;

SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, (
        CASE 
            WHEN STATUS = "RESERVED" THEN "예약중"
            WHEN STATUS = "DONE" THEN "거래완료"
            WHEN STATUS = "SALE" THEN "판매중" END) AS STATUS 
FROM USED_GOODS_BOARD
WHERE YEAR(CREATED_DATE) = 2022 AND MONTH(CREATED_DATE) = 10 AND DAY(CREATED_DATE) = 5
ORDER BY BOARD_ID DESC