-- 완료된 중고 거래의 총금액이 70만원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
-- order by 총거래금액 asc

SELECT U.USER_ID, U.NICKNAME, P.TOTAL_PRICE AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (SELECT SUM(PRICE) AS TOTAL_PRICE, WRITER_ID
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID) P -- GROUP BY 전에 WHERE 절로 미리 필터 걸어서 완료된 것 기준으로 WRITER_ID 를 하는게 좋다! 
ON U.USER_ID = P.WRITER_ID
WHERE P.TOTAL_PRICE >= 700000
ORDER BY TOTAL_SALES 
