SELECT CN.APNT_NO, P.PT_NAME, CN.PT_NO, CN.MCDP_CD, D.DR_NAME, CN.APNT_YMD
FROM PATIENT P, DOCTOR D, (SELECT APNT_NO, APNT_YMD, PT_NO, MCDP_CD, MDDR_ID, APNT_CNCL_YN, APNT_CNCL_YMD
                           FROM APPOINTMENT
                           WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N') CN
WHERE (P.PT_NO = CN.PT_NO AND D.DR_ID = CN.MDDR_ID)
ORDER BY CN.APNT_YMD ASC;

-- 날짜의 타입을 항상 잘 보자 ! 뒤에 숫자가 붙어있으면 APNT_YMD = '2022-04-13' 으로는 찾을 수가 없는 것 